### ISSUE TITLE
外枠まで掘れるのでハングする

### ISSUE THREAD

**Issue by c0a2106423** [c0a21010/ProjExD#10]
https://github.com/c0a21010/ProjExD/blob/8215365bc599567bd6536781073319eb28eb8d89/ex3/maze.py#L135

外枠を掘り、画面外方向に移動すると、"list index out of range"でハングする

**Comment by c0a2106423** [comment]
下端、右端の壁の場合に発生する。

**Comment by c0a21010** [comment]
修正方法が今のところ思いつかないので保留でお願いします。
