### ISSUE TITLE
クラス関数について

### ISSUE THREAD

**Issue by C0A21070** [c0a21010/ProjExD#12]
https://github.com/c0a21010/ProjExD/blob/8215365bc599567bd6536781073319eb28eb8d89/ex3/maze.py#L19
クラス関数を用いてユーザー関数を集約させていることはいいのだが、mainのところでいちいちクラス関数内を見るのは大変だと思う。

**Comment by c0a21010** [comment]
コードの検索機能などを使うことをおすすめします
