### ISSUE TITLE
爆弾の動く範囲

### ISSUE THREAD

**Issue by C0A21070** [c0a21010/ProjExD#13]
https://github.com/c0a21010/ProjExD/blob/a14a27da362762899fedeec7807b3e1296d27f6c/ex04/dodge_bomb.py#L29
x=rd.randint(0, screen_rct.width)にすると、画面サイズが変わっても対応できると思う。

**Comment by c0a21010** [comment]
修正します

**Comment by c0a21010** [comment]
修正しました
