### ISSUE TITLE
コード内のマジックナンバーについて

### ISSUE THREAD

**Issue by Inazuma110** [c0a21010/ProjExD#16]
この900,1600という値は，画面の端を表す値だと思いますが，マジックナンバーになってしまいます．(参考: https://xtech.nikkei.com/it/article/COLUMN/20070820/279836

画面の幅と高さは，それを取得する関数を探して使ってみてください．

https://github.com/c0a21010/ProjExD/blob/0927a5e77eb3a019732af5fbffee53f66213b610/ex04/dodge_bomb.py#L43-L46

**Comment by c0a21010** [comment]
修正しました
