### ISSUE TITLE
for文で回すという選択肢は？

### ISSUE THREAD

**Issue by c0a2106423** [c0a21010/ProjExD#8]
https://github.com/c0a21010/ProjExD/blob/2b1c943e41ff314c80efe30a5af32525cd1aacb9/ex02/calc.py#L95

listにまとめて 
for i in "list_name" : で処理出来る気がします。
コードがゴチャる気がしないでもないですが…

**Comment by c0a21010** [comment]
了解です。やってみます。

**Comment by c0a21010** [comment]
修正しました
